### ISSUE TITLE
Trouble understanding

### ISSUE THREAD

**Issue by Jeya27** [adamnicholson/flatbase#10]
I am a complete newbie for flat databases and PHP. I have trouble creating database and inserting record in it.I get a lot of errors thrown..........I'm not sure what is the path i must give for 'path/for/storage/dir'. I'm having trouble running it in console too.

I find flatbase easy to relate with sql queries and easy to understand the code,but a simple example or pointing out where I'm going wrong would be of great help.

I am planning on using this flatbase flat file database for storing the users who change password. It's like log to my page. Any suggestions are welcome.

Thank You.

I use PHP 7.2

Code :  

`

1. <?php
2. 
3. use Flatbase\Exception\Exception;
4. use Flatbase\Handler\DeleteQueryHandler;
5. use Flatbase\Handler\InsertQueryHandler;
6. use Flatbase\Handler\ReadQueryHandler;
7. use Flatbase\Handler\UpdateQueryHandler;
8. use Flatbase\Query\DeleteQuery;
9. use Flatbase\Query\InsertQuery;
10. use Flatbase\Query\Query;
11. use Flatbase\Query\ReadQuery;
12. use Flatbase\Query\UpdateQuery;
13. use Flatbase\Storage\Filesystem;
14. use Flatbase\Storage\Storage;
15. use Flatbase\Flatbase;
16. use Flatbase\Collection;
17. 
18. $storage = new Flatbase\Storage\Filesystem('/home/user/Flatdb/Logs/users');
19. $flatbase = new Flatbase\Flatbase($storage);
20. 
21. $flatbase->insert()->in('users')->set(['name' => 'Adam', 'height' => "6'4"])->execute();
22. 
23. $flatbase->read()->in('users')->where('name', '=', 'Adam')->first();
24. ?>

`

**Comment by Jeya27** [comment]
I get the Error:

` PHP Fatal error:  Uncaught Error: Class 'Flatbase\Flatbase\Storage\Filesystem' not found in /home/user/Flatdb/try.php:24
Stack trace:
#0 {main}
  thrown in /home/user/Flatdb/try.php on line 18
`
Though I have added Flatbase/Storage/Filesystem.......You may suggest I can try adding Flatbase\Flatbase\Storage\Filesystem......... I tried that too.......but still got the same error...

**Comment by moeenio** [comment]
Are you sure flatbase is correctly installed? If yes, make sure to add the Composer autoload thing at the top of your file, like so :
```php
require __DIR__ . '/vendor/autoload.php';
```
More on this [here](https://getcomposer.org/doc/01-basic-usage.md#autoloading).
@Jeya27

**Comment by Jeya27** [comment]
Thank you for your help @locness3

**Comment by moeenio** [comment]
I think you should close this issue now ;)
